### PR TITLE
AsyncAPI v3

### PR DESCRIPTION
**Pull request by ChMThiel**
Hi @fjtirado, 

I updated the dependency in root-pom for `version.asyncapi.core`to 1.0.0-RC and made the necessary changes in ,y Scanner-modules.

To be able to compile & test my changes, i temporarily disabled your modules by documenting the module in the root-pom:
grafik

Please have a look and at your part of the code to make it AsyncAPI v3 compliant.

What do you think - should we make a new release when you're finished ? It's a breaking change...so it might be a step to v1.0.0.

Best regards,
Christian

### CODE REVIEW

**Comment by ChMThiel** [comment]
@fjtirado 
the build fails, because i documeted your part out but the doc-module tries to get some stuff from there...
It should be fine as soon as you re-add your modules...

**Comment by fjtirado** [comment]
@ChMThiel Ok, let me do a PR over this PR (reenable and change), once merged I will release

**Comment by fjtirado** [comment]
Fixes https://github.com/quarkiverse/quarkus-asyncapi/issues/182

**Comment by ChMThiel** [comment]
@fjtirado Please see [Bug in asyncapi-core](https://github.com/asyncapi/jasyncapi/issues/198#issuecomment-2098857186)
...but asyncapi-core 1.0.0-RC2 is no released yet. We should update the dependency if available - even if that means some refactorings (again)

**Comment by fjtirado** [comment]
@ChMThiel Then I think the wisest path is to not merge this till the new release is available. Im currently working on the PR over your PR for the config part...

**Comment by fjtirado** [comment]
@ChMThiel Just in case you did not see it https://github.com/quarkiverse/quarkus-asyncapi/pull/185

**Comment by ChMThiel** [comment]
@fjtirado now we have to wait for the release of asyncapi-core....

**Review by fjtirado — APPROVED** [review]

**Pull request merged**
