### PR TITLE
Reverting back source codegen

### PR DESCRIPTION
**Pull request by fjtirado**

### CODE REVIEW

**Comment by ChMThiel** [comment]
@fjtirado Hi, i added some important fixes&improvements in the scanner-part of the extension 
(see https://github.com/quarkiverse/quarkus-asyncapi/pull/105 and https://github.com/quarkiverse/quarkus-asyncapi/pull/102)
I'd like to create a new minor-version v 0.2.0 for that, but is saw that you are currently working on your side.
Is the new version ok for you?

**Comment by fjtirado** [comment]
> @fjtirado Hi, i added some important fixes&improvements in the scanner-part of the extension (see #105 and #102) I'd like to create a new minor-version v 0.2.0 for that, but is saw that you are currently working on your side. Is the new version ok for you?

Yes, but lets wait till I have finished

**Comment by ChMThiel** [comment]
> > @fjtirado Hi, i added some important fixes&improvements in the scanner-part of the extension (see #105 and #102) I'd like to create a new minor-version v 0.2.0 for that, but is saw that you are currently working on your side. Is the new version ok for you?
> 
> Yes, but lets wait till I have finished

I will go on holiday tomorrow for 3 weeks.  But my colleagues are waiting for my fixes...
If you need longer, could you do me a favor and make the new version, when you are finished?

**Comment by fjtirado** [comment]
@ChMThiel sure, Ill do it tomorrow. Just commit your changes and I will be publishing 0.2.0 as soon as possible

**Pull request merged**
